diameter path of edges
igraph/igraph pull request #1673
Opened 2021-02-17 19:30 UTC by guyroznb

answers issue #1542 - returning the path of the diameter in terms of edges and / or vertices.

thanks

2021-02-17 22:06 UTC, szhorvat commented
I changed the base to `develop` again. Since this PR changes the API, it's going to be merged into `develop`, and will become part of the next version, 0.10.  This change should not affect you in any way.

2021-02-18 07:12 UTC, szhorvat requested changes
Thanks for the contribution! I added a few comments.

Additionally, can you add a few more tests? We should test:

 - The graph with zero vertices.
 - The graph with a single vertex.
 - A disconnected graph both with `unconn=true` and `unconn=false`.
 
This will produce Inf and NaN results. These should be printed using `print_real` from test_utilities as `print_real(stdout, x, "%g")`. (Not `printf`, as `printf`'s output is platform-dependent).

2021-02-18 07:12 UTC, szhorvat commented on tests/unit/igraph_diameter.c
> +    igraph_barabasi_game(&g, 30, /*power=*/ 1, 30, 0, 0, /*A=*/ 1,
Here we need to set a random seed, so make the test output deterministic. Something like:

```
igraph_rng_seed(igraph_rng_default(), 1234);
```

2021-02-18 07:12 UTC, szhorvat commented on tests/unit/igraph_diameter.c
> +*/
Please use this updated copyright notice:

https://github.com/igraph/igraph/blob/master/tests/unit/igraph_st_mincut.c#L2

2021-02-18 07:12 UTC, szhorvat commented on tests/unit/igraph_diameter.c
> +    igraph_barabasi_game(&g, 30, /*power=*/ 1, 30, 0, 0, /*A=*/ 1,
Additionally, let's print another header here, something like `printf("diameter of Barabasi graph:\n");`

2021-02-18 07:12 UTC, szhorvat commented on tests/unit/igraph_diameter.c
> +    printf("diameter: %li, from %li to %li\n", (long int) result,
Let us print the `result` as a `%g`, without casting to a `long int` (both here and below). It will not change the output.

2021-02-18 07:14 UTC, szhorvat commented on src/paths/shortest_paths.c
>          } else {
Here too, let us update the `else` branch to use `igraph_get_shortest_path` instead of `igraph_get_shortest_paths`.

2021-02-19 13:06 UTC, ntamas commented
Looks like there are some genuine test failures so I'm putting this into draft state until these are resolved.

@guyroznb Feel free to mark it as "ready for review" when the test failures are fixed.

2021-02-21 18:04 UTC, szhorvat requested changes
Thanks for the update! I added a few more comments, the main one being that we do not need an `if` with three branches when getting the actual path (am I missing some reason why you added the branches?).

2021-02-21 18:04 UTC, szhorvat commented on src/paths/shortest_paths.c
> +            }
It seems to me that we don't need if `if ... else` construct here. Just call `igraph_get_shortest_path` directly with `vertex_path` and `edge_path`.

2021-02-21 18:04 UTC, szhorvat commented on src/paths/shortest_paths.c
> +            }
It seems to me that we don't need if `if ... else` construct here. Just call `igraph_get_shortest_path` directly with `vertex_path` and `edge_path`.

2021-02-21 21:03 UTC, guyroznb commented
thanks @szhorvat and @ntamas for the review!

2021-02-22 08:21 UTC, szhorvat approved these changes

2021-02-23 15:22 UTC, ntamas approved these changes

2021-02-23 15:22 UTC, merged

2021-02-23 15:22 UTC, ntamas commented
Thanks a lot for the PR, much appreciated!