Use matching vectors for hub and authority
igraph/igraph pull request #1813
Opened 2021-09-22 11:59 UTC by GroteGnoom

Also adds tests.

Fixes #1424
Fixes #1591

This implementation is not the most efficient, but I tried to produce something correct to see if this produces the expected results.

I changed the Kleinberg functionality for edgeless graphs to be consistent with other results, because I was surprised by it.

In practice the hub and authority eigenvalues seem to be the same, I can prove it for a 2x2 matrix, but I didn't prove it for larger matrices. I guess the proof could be one-liner, so I hope someone who is a bit better at linear algebra can confirm this.

2021-09-22 12:50 UTC, szhorvat commented
A comment and some questions on:

> - `igraph_hub_and_authority_scores()` calculates the hub and authority scores of a graph as a matching pair.

Is this achieved with the following line?

   igraph_vector_fill(vector, 1.0 / no_of_nodes);

----

In most cases, ARPACK appears to return eigenvectors which are normalized so that their Euclidean norm is 1. A vector consisting of `1.0 / no_of_nodes` is not normalized this way. For that we need `1.0 / sqrt(no_of_nodes)`.

However, I believe (have to check!) that ARPACK does not _guarantee_ returning normalized results. Therefore, igraph should not guaratee this either. The hub and authority scores functions have the `scale` feature, which is a kind of normalization: it normalizes so that the largest value is 1. When `scale=false`, we should make no promises about normalization.

In fact, there is a test which tends to fail on Windows when using external BLAS/LAPACK (discussed in #1491, I think). The result is not in fact incorrect, just not normalized as usual. It was never clear if this should be considered a bug or not.

My suggestion is:

 - We can include the normalization fix if you like, but use `1.0 / sqrt(no_of_nodes)`.
 - Do not mention the fix in the changelog. Mentioning it makes it look like igraph makes guarantees about the normalization, but it does not.
 - Make it explicit in the docs that nothing is guaranteed about normalization.

@GroteGnoom Am I misunderstanding anything?

2021-09-22 13:51 UTC, szhorvat commented
I'll have to look carefully at the matrix multiplication you do to obtain one score from the other. I just wanted to note that I have the impression that it will not work correctly for an undirected graph because of the use of `IGRAPH_TO`.

Could we not just re-use the same `igraph_i_kleinberg_unweighted` and `igraph_i_kleinberg_weighted` functions to do the multiplication? That's what these functions do.

2021-09-22 13:52 UTC, szhorvat commented
Sorry, to be clear: these scores make little sense for undirected graphs, but currently they _do_ work and should return the same result as for a directed graph with all-reciprocal edges. We should not break this.

2021-09-22 14:02 UTC, GroteGnoom commented
> @GroteGnoom Am I misunderstanding anything?

No, I forgot the sqrt, and didn't realize normalization isn't guaranteed. I don't want to change things without a changelog, even if we didn't guarantee a specific outcome. If the vectors returned by ARPACK are not always normalized in practice, then it seems better to just keep the old behavior.

2021-09-23 19:16 UTC, szhorvat commented
Is it ready / shall I take another look?

2021-09-23 19:22 UTC, GroteGnoom commented
Oh, I completely forgot about it after sending it through the CI, yes please, I'm definitely interested in your comments for this new version.

2021-09-23 19:30 UTC, szhorvat commented
One small comment:

I was thinking about the long name `hub_and_authority_scores` and noticed that both networkx and Mathematica call it "HITS", which is more concise. I was wondering if we should consider this as well. However, both Wikipedia and Newman's book seem to use "HITS" to refer not to the scores, but to the iterative algorithm to compute them. We don't use this algorithm, so perhaps we should not use the name "HITS" either.

2021-09-23 19:52 UTC, GroteGnoom commented
Maybe we should just remove the "scores". That should help, and I don't think it makes it any less clear.

2021-09-23 20:03 UTC, szhorvat commented
I think it's fine as it is, was just thinking aloud.

2021-09-24 09:28 UTC, ntamas commented on src/centrality/hub_authority.c
> +            igraph_vector_resize(hub_vector, no_of_nodes);
We probably need an `IGRAPH_CHECK()` around here

2021-09-24 09:28 UTC, ntamas commented on src/centrality/hub_authority.c
> +            igraph_vector_resize(authority_vector, no_of_nodes);
We probably need an `IGRAPH_CHECK()` around here

2021-09-24 09:28 UTC, ntamas commented on src/centrality/hub_authority.c
> +                igraph_vector_resize(hub_vector, no_of_nodes);
We probably need an `IGRAPH_CHECK()` around here

2021-09-24 09:29 UTC, ntamas commented on src/centrality/hub_authority.c
> +                igraph_vector_resize(authority_vector, no_of_nodes);
We probably need an `IGRAPH_CHECK()` around here

2021-09-24 09:31 UTC, ntamas requested changes
I'll fix the `iGRAPH_CHECK()` issues that I commented about and then I'll merge, thanks!

2021-09-24 09:33 UTC, merged