feat: support isoclasses for 5 and 6 vertex undirected graphs
igraph/igraph pull request #1902
Opened 2021-12-26 17:46 UTC by szhorvat

2021-12-26 22:25 UTC, szhorvat commented
This is ready for general feedback, as it seems to be working correctly now, but I'll still make a few changes to simplify test code. The main test, which was modified here, will use a smaller graph so reduce the running time (LAD is slow at these motif sizes).

2021-12-26 22:45 UTC, szhorvat commented
There's the question of where to put the code I used to create the lookup tables. It's written in Mathematica. We should keep it, otherwise it will be a pain to re-do everything from scratch next time we need to touch this functionality. I was hoping to make it short enough to insert it in comments, but that didn't quite work out.

2021-12-27 10:26 UTC, ntamas commented
> There's the question of where to put the code I used to create the lookup tables.

Put them in `tools`; this is where we keep the LAPACK patches (I doubt that they still work, though) and an ARPACK-related `sed` script.

2021-12-27 16:55 UTC, szhorvat commented
@ntamas When you review this, please read the comment I added at the top of `isoclasses.c` and let me know if it is understandable. I'll add the lookup table generator a bit later. Let me know if you're happy with this and I'll do the merge (including the merge into develop). Please don't "squash-and-merge". The commits here are many, but clean.

2021-12-28 14:36 UTC, szhorvat commented
The reason for the reduced coverage in LAD is that I reduced the graph sizes in the `example::igraph_subisomorphic_lad` test. This test was already the slowest. With the larger motifs I added, it now takes 3.5 seconds when compiled with all optimizations.

2021-12-28 21:19 UTC, ntamas requested changes
Looks good to me in general, but I have to trust you that the generated tables are correct :) Can you also add the Mathematica code that generated the tables?

2021-12-28 21:19 UTC, ntamas commented on src/isomorphism/isoclasses.c
>          (igraph_integer_t) number, directed ? "directed" : "undirected", (igraph_integer_t) size)
The total number of graphs of a given size is missing from the argument list of `IGRAPH_ERRORF`.

2021-12-28 21:19 UTC, ntamas commented on src/isomorphism/isoclasses.c
> + * if set, represents edge i-j in the grah code.
Typo here: `grah` -> `graph`

2021-12-28 21:38 UTC, szhorvat commented
@ntamas These two are fixed. I'll refrain from force-pushed while you're reviewing, but I'll clean up the commits afterwards.

2021-12-28 21:53 UTC, ntamas approved these changes

2021-12-28 21:53 UTC, ntamas commented
Feel free to force-push and then merge, it seems okay to me now!

2021-12-28 22:01 UTC, szhorvat commented
@ntamas Can you merge `master` into `develop` _before_ I merge this, so I can avoid any plfit-related merge conflicts when I later work on merging this into develop?

2021-12-28 22:29 UTC, merged