Add igraph_is_biconnected() to decide whether a graph is biconnected
igraph/igraph pull request #2470
Opened 2024-01-29 12:35 UTC by ntamas

As requested in https://github.com/igraph/igraph/issues/2469

2024-01-29 12:50 UTC, szhorvat commented
Let's figure out the edge cases:

 - The null graph is not connected, so also not biconnected
 - We'll probably agree that the singleton should not be biconnected
 - I'm not so sure about what to do with $K_2$ ...

2024-01-29 16:07 UTC, ntamas commented
Re $K_2$, the documentation of `igraph_biconnected_components()` already settles this:

> Note that some authors do not consider the graph consisting of two connected vertices as biconnected, however, igraph does.

I guess we should just stick to this.

2024-01-29 16:16 UTC, szhorvat commented
### Arguments for treating $K_2$ as biconnected

 - If we partition the edges of the graph into disjoint biconnected components, $K_2$ will have a _single_ component

### Survey on how other packages treat $K_2$

#### Mathematica: `False`

```
In[21]:= KVertexConnectedGraphQ[CompleteGraph[2], 2]
Out[21]= False

In[22]:= KVertexConnectedComponents[CompleteGraph[2], 2]
Out[22]= {}

In[23]:= KVertexConnectedComponents[PathGraph[{1, 2, 3}], 2]
Out[23]= {{1, 2}, {2, 3}}
```

I find it strange that some of the vertices of $K_2$ belong to no biconnected component according to Mathematica.

#### NetworkX: `True`

<img width="392" alt="image" src="https://github.com/igraph/igraph/assets/1212871/a6411434-14de-41f5-a0c3-5fbdadb65bb9">

2024-01-29 16:40 UTC, szhorvat commented
@ntamas I wrote up some argument in favour / against treating $K_2$ as biconnected. This is rather messy, but I'm leaning towards treating it as biconnected because we want to stay consistent with `igraph_biconnected_components()`, and I'd like to say that every edge is part of precisely one biconnected component. (We don't say the same about vertices: isolated vertices are not part of any biconnected component.)

I would suggest treating graphs with fewer than 3 vertices separately in the implementation, and not touching the cache for such small graphs. One issue we have is that $K_2$ will be biconnected, yet it's still acyclic / a forest.

All this issues should be written up in the docs.

What do you think?

2024-01-29 16:48 UTC, szhorvat commented
> > Note that some authors do not consider the graph consisting of two connected vertices as biconnected, however, igraph does.
> 
> I guess we should just stick to this.

I'm sorry, I didn't notice this. It seems we agree then.

2024-01-29 16:57 UTC, szhorvat requested changes
A few nitpick changes and one big one:

The cache use is currently invalid for $K_2$, which is both biconnected and acyclic. Let us not touch the cache at all if the vertex count `n` is less than 3. There should be a separate code path for the `n < 3` case.

`n == 0` and `n == 1` are easy: not biconnected.

For `n == 2`, I'm not sure what's the simplest solution. We could iterate through edges until we find an edge connecting the two vertices. If we found one, then the graph is biconnected.  But this is not simple code given that it handles just one specific case.

Alternatively, the caching part could be guarded by an `if (n >= 3)` (both reading and setting the cache). Then the main code can handle `n == 2` correctly.

We should add comments in the source code about the special `n == 2` case.

2024-01-29 16:57 UTC, szhorvat commented on examples/simple/igraph_is_biconnected.c
> +*/
```suggestion
/*
   IGraph library.
   Copyright (C) 2024  The igraph development team <igraph@igraph.org>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
```

2024-01-29 16:57 UTC, szhorvat commented on src/connectivity/components.c
> + * \param result If not a NULL pointer, the result will be returned here.
```suggestion
 * \param result If not a \c NULL pointer, the result will be returned here.
```

2024-01-29 16:57 UTC, szhorvat commented on tests/unit/igraph_is_biconnected.c
> +*/
```suggestion
/*
   IGraph library.
   Copyright (C) 2024  The igraph development team <igraph@igraph.org>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
```

2024-01-29 19:35 UTC, szhorvat commented
Let's also add this to `functions.yaml`.

2024-01-29 22:29 UTC, szhorvat commented on src/connectivity/components.c
> + * have any articulation points, otherwise it has at least one.
This is not quite accurate. Once again $K_2$ has no articulation points yet it is biconnected.

Suggestion:

```suggestion
 * Use \ref igraph_is_biconnected() if you are only interested in whether the
 * graph has precisely one biconnected component.
```

2024-01-30 06:48 UTC, ntamas commented
Ready for another round here.

2024-01-30 09:07 UTC, szhorvat approved these changes

2024-01-30 09:07 UTC, szhorvat commented on src/connectivity/components.c
> +    if (is_biconnected && no_of_nodes > 2) {
```suggestion
    if (is_biconnected && no_of_nodes >= 3) {
```

Just for consistency with the lines at the top that read the cache.

2024-01-30 09:13 UTC, merged

2024-01-30 09:32 UTC, szhorvat commented
Do you mind if I backport this to `master` and add it to Python?

2024-01-30 09:55 UTC, ntamas commented
Nope, actually I started this on `master` but then I realized that there isn't an `Added` section yet in the changelog and did not want to start one. But if you need this, then sure, go ahead.

You can use the code for `igraphmodule_Graph_is_connected()` as an inspiration for `is_biconnected()`.

2024-01-30 10:52 UTC, szhorvat commented
Backport done. I marked it as experimental on `master` only (not on `develop`). Just in case ...