refactor!: igraph_get_biadjacency() now takes a weights parameter
igraph/igraph pull request #2577
Opened 2024-04-17 20:01 UTC by szhorvat

This completes the breaking portion of #2414 so we can make progress towards 1.0.

2024-04-18 10:11 UTC, szhorvat commented
@ntamas Can you have a look? Let me know what you think about #2579, and let's do that change here as well.

2024-04-19 09:59 UTC, ntamas requested changes
Looks good to me in general; I only proposed fixes for a few typos

2024-04-19 09:59 UTC, ntamas commented on src/misc/bipartite.c
> + * \param biadjmatrix The bipartite adjacency matrix that serves as an biadjmatrix
`an biadjmatrix` is grammatically incorrect

2024-04-19 09:59 UTC, ntamas commented on src/misc/bipartite.c
> +                "Bipartite adjacencey matrix elements should be non-negative, found %g.",
typo here; should be `adjacency`

2024-04-22 06:39 UTC, ntamas approved these changes
LGTM.

2024-04-22 08:08 UTC, merged